"""Add metadata field to events

Revision ID: 767ca726d6a2
Revises: 001
Create Date: 2025-12-03 17:38:31.088610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767ca726d6a2'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_automation_rules_id'), 'automation_rules', ['id'], unique=False)
    op.create_index(op.f('ix_event_attendees_id'), 'event_attendees', ['id'], unique=False)
    op.add_column('events', sa.Column('metadata', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_task_assignees_id'), 'task_assignees', ['id'], unique=False)
    op.create_index(op.f('ix_task_comments_id'), 'task_comments', ['id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_id'), 'task_dependencies', ['id'], unique=False)
    op.create_index(op.f('ix_task_tags_id'), 'task_tags', ['id'], unique=False)
    op.create_index(op.f('ix_task_watchers_id'), 'task_watchers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_watchers_id'), table_name='task_watchers')
    op.drop_index(op.f('ix_task_tags_id'), table_name='task_tags')
    op.drop_index(op.f('ix_task_dependencies_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_comments_id'), table_name='task_comments')
    op.drop_index(op.f('ix_task_assignees_id'), table_name='task_assignees')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_column('events', 'metadata')
    op.drop_index(op.f('ix_event_attendees_id'), table_name='event_attendees')
    op.drop_index(op.f('ix_automation_rules_id'), table_name='automation_rules')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    # ### end Alembic commands ###

